spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot-learning?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: root
    password: 28186612
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.potato.boot.mybatis.domain
  configuration:
    map-underscore-to-camel-case: true
